### ISSUE TITLE
Erreur commande init db

### ISSUE THREAD

**Issue by guywiz** [Hisqkq/Projet-de-visualisation-M1#5]
La commande indiquée pour initialiser la base de données est incorrecte. Le script python `initialize_db.py` est à la racine, il faut donc faire `python initialize_db.py`. Pas méchant, mais à corriger dans le README.

**Comment by Hisqkq** [comment]
> La commande indiquée pour initialiser la base de données est incorrecte. Le script python `initialize_db.py` est à la racine, il faut donc faire `python initialize_db.py`. Pas méchant, mais à corriger dans le README.

Merci pour la remarque, c'est modifié dans le README.
